import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import * as solanaWeb3 from '@solana/web3.js';
import { encodeURL, createQR } from '@solana/pay';
import { useEffect, useState, useRef } from 'react';
import {
  Button,
  ButtonGroup,
  Input,
  Box,
  Flex,
  Text,
  Grid,
  GridItem,
  RadioGroup,
  Stack,
  Radio,
  Spinner,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
} from '@chakra-ui/react';
import BigNumber from 'bignumber.js';
import { create } from 'domain';
import Checkout from '@/components/Checkout';
import SolGasFeeCalculator from '@/components/SolGasFeeCalculator';

const inter = Inter({ subsets: ['latin'] });
const Home = () => {
  const [hasPaid, setHasPaid] = useState<Boolean>(false);
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState<boolean>(false);
  const [transactionLimit, setTransactionLimit] = useState<number>(500);
  const [address, setAddress] = useState<string>('');

  const handleSetAddress = (address: string) => {
    setAddress(address);
  };
  const handleSetTransactionLimit = (transactionLimit: number) => {
    setTransactionLimit(transactionLimit);
  };

  const handlePayOpen = () => {
    setIsPaymentModalOpen(true);
  };

  const handlePayClose = () => {
    setIsPaymentModalOpen(false);
  };

  const updateHasPaid = (newValue: boolean) => {
    setHasPaid(newValue);
  };

  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>My SOL Dashboard</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>SOL Gas Fee Calculator&nbsp;</p>
          <div>
            <a href='' target='_blank' rel='noopener noreferrer'>
              By <code>Kique Fungus</code>
            </a>
          </div>
        </div>

        <Modal isOpen={isPaymentModalOpen} onClose={handlePayClose}>
          <ModalOverlay />
          <ModalContent minWidth={512}>
            <ModalHeader
              display='flex'
              alignContent='center'
              justifyContent='center'
              color='black'
            >
              Checkout
            </ModalHeader>
            <ModalCloseButton />
            <ModalBody
              display='flex'
              justifyContent='center'
              alignContent='center'
              alignItems='center'
            >
              <Checkout
                updateHasPaid={updateHasPaid}
                onClose={handlePayClose}
                transactionLimit={transactionLimit}
                address={address}
              />
            </ModalBody>

            <ModalFooter display='flex' justifyContent='center'>
              <Button colorScheme='blue' mr={3} onClick={handlePayClose}>
                Back
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>

        <Flex
          // display='center'
          flexDirection='column'
          align='center'
          justify='center'
          position='relative'
          padding='2rem 0'
          margin='5px'
        >
          <SolGasFeeCalculator
            updateHasPaid={updateHasPaid}
            onOpen={handlePayOpen}
            handleSetTransactionLimit={handleSetTransactionLimit}
            handleSetAddress={handleSetAddress}
            hasPaid={hasPaid}
            transactionLimit={transactionLimit}
            address={address}
          />
        </Flex>

        <div className={styles.grid}>
          {/* <a
            href='https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
            target='_blank'
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a> */}
        </div>
      </main>
    </>
  );
};

export default Home;
